name: 'Lighthouse Diff'
description: 'Compare Lighthouse scores between baseline and current URLs'
author: 'Katie'

branding:
  icon: 'activity'
  color: 'yellow'

inputs:
  baseline-url:
    description: 'Baseline URL to audit'
    required: true
  current-url:
    description: 'Current URL to audit'
    required: true
  config-path:
    description: 'Path to config file'
    required: false
  threshold-performance:
    description: 'Minimum performance score'
    required: false
  threshold-accessibility:
    description: 'Minimum accessibility score'
    required: false
  threshold-best-practices:
    description: 'Minimum best practices score'
    required: false
  threshold-seo:
    description: 'Minimum SEO score'
    required: false

outputs:
  markdown:
    description: 'Results formatted as markdown'
    value: ${{ steps.diff.outputs.markdown }}
  passed:
    description: 'Whether thresholds passed (true or false)'
    value: ${{ steps.diff.outputs.passed }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install lighthouse-diff
      shell: bash
      run: npm install -g lighthouse-diff
    
    - name: Run comparison
      id: diff
      shell: bash
      run: |
        # Build command with options
        CMD="lighthouse-diff compare '${{ inputs.baseline-url }}' '${{ inputs.current-url }}'"
        CMD="$CMD --format markdown --ci"
        
        if [ -n "${{ inputs.config-path }}" ]; then
          CMD="$CMD --config '${{ inputs.config-path }}'"
        fi
        
        if [ -n "${{ inputs.threshold-performance }}" ]; then
          CMD="$CMD --threshold-performance ${{ inputs.threshold-performance }}"
        fi
        
        if [ -n "${{ inputs.threshold-accessibility }}" ]; then
          CMD="$CMD --threshold-accessibility ${{ inputs.threshold-accessibility }}"
        fi
        
        if [ -n "${{ inputs.threshold-best-practices }}" ]; then
          CMD="$CMD --threshold-best-practices ${{ inputs.threshold-best-practices }}"
        fi
        
        if [ -n "${{ inputs.threshold-seo }}" ]; then
          CMD="$CMD --threshold-seo ${{ inputs.threshold-seo }}"
        fi
        
        # Run and capture output
        set +e
        OUTPUT=$(eval $CMD 2>&1)
        EXIT_CODE=$?
        set -e
        
        # Set outputs
        echo "markdown<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        if [ $EXIT_CODE -eq 0 ]; then
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "passed=false" >> $GITHUB_OUTPUT
        fi
        
        # Write to step summary
        echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
        
        # Exit with original code
        exit $EXIT_CODE
